Ets node info
mkacper/erlangpl pull request #1
Opened 2017-05-30 10:07 UTC by mkacper

This PR allows to render very simple ETS graph in erlangpl web UI. The graph shows basic ETS information from observed node. In order to see how it works build this PR (both erlangpl and ui), start to observe a node and then go to http://localhost:37575/ets.
Please let me know what do you think :)

2017-05-30 10:40 UTC, baransu requested changes
I cannot review it properly because of my limited erlang knowladge but from JS point of view it's ok. If you could please remove unused assets and `.json` file from both ets and vizceral plugins.

2017-05-30 10:40 UTC, Baransu commented on ui/src/plugins/epl-ets/sample_data.json
> +{
You can delete this file from since we're not using it. You can delete the same file from `epl-vizceral` too.

2017-05-30 10:40 UTC, Baransu commented on ui/src/App.js
> +    { path: '/ets', icon: 'share-alt' },
It would be better not to have 2 the same icons.

2017-05-30 11:18 UTC, mkacper commented on ui/src/plugins/epl-ets/sample_data.json
> +{
> unused assets

What do you mean?

2017-05-30 12:02 UTC, Baransu commented on ui/src/plugins/epl-ets/sample_data.json
> +{
Images for example

2017-05-31 17:31 UTC, michalslaski requested changes

2017-05-31 17:31 UTC, michalslaski commented on apps/epl/src/epl_viz_map.erl
> +
Good idea to create a new module epl_viz_map.erl with all Vizceral specific functionality. Please add -spec to all exported functions.

2017-05-31 17:31 UTC, michalslaski commented on apps/epl_ets/src/epl_ets.erl
> +    ETSMemUsage = get_ets_mem_usage(),
Maybe instead of calling erlang:memory/0 through epl_tracer:command(), change epl_tracer:handle_info() so that it collects all memory statistics.

2017-05-31 17:31 UTC, michalslaski commented on apps/epl_ets/src/epl_ets_viz_map.erl
> +%%%-------------------------------------------------------------------
Let's keep all functionality related to Vizceral maps in apps/epl/src/epl_viz_map.erl as other modules/applications can reuse it in the future.

2017-06-22 10:59 UTC, merged